"""
Notebook Renderer

This module converts stepwise pipeline code into a Jupyter Notebook.

Rules (from V3.1_PRD.md):
- Use nbformat v4
- Perform ZERO business logic
- Perform ZERO data inspection
- Notebook is a RENDERER, not a new pipeline
- Must reuse generate_stepwise_code() - duplicating logic is a BUG
"""

import nbformat
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell
from pathlib import Path

from .manifest import load_manifest
from .generator import generate_stepwise_code


TEMP_STORAGE = Path(__file__).parent.parent / "temp_storage"


def generate_notebook(session_id: str) -> nbformat.NotebookNode:
    """
    Generate a Jupyter Notebook from the session manifest.
    
    The notebook contains:
    1. Header markdown cell
    2. Imports code cell
    3. Load data code cell
    4. For each pipeline step: markdown + code cell pair
    5. Export results cell (if split exists)
    
    Args:
        session_id: The session UUID
    
    Returns:
        nbformat.NotebookNode: The notebook object
    
    Raises:
        FileNotFoundError: If session or manifest not found
    """
    session_path = TEMP_STORAGE / session_id
    
    if not session_path.exists():
        raise FileNotFoundError(f"Session {session_id} not found")
    
    manifest = load_manifest(session_path)
    
    if manifest is None:
        raise FileNotFoundError(f"Pipeline manifest not found for session {session_id}")
    
    # Get stepwise code from the SINGLE interpreter
    stepwise_code = generate_stepwise_code(manifest)
    
    # Check if there's a split step
    has_split = any(step["step_type"] == "split" for step in stepwise_code)
    
    # Determine required imports
    imports = _determine_imports(stepwise_code)
    
    # Create notebook
    nb = new_notebook()
    
    # Set kernel metadata
    nb.metadata = {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        }
    }
    
    cells = []
    
    # Cell 1: Header (Markdown)
    header_md = """# ML Preprocessing Pipeline

This notebook was generated by **ML Preprocessing Tool**.

**Source of truth**
- Pipeline manifest: `pipeline.json`
- Input data: `input.csv`

This notebook is deterministic:
same input + same steps = same output."""
    cells.append(new_markdown_cell(header_md))
    
    # Cell 2: Imports (Code)
    cells.append(new_code_cell(imports))
    
    # Cell 3: Load Data (Code)
    load_code = """df = pd.read_csv("input.csv")
df.head()"""
    cells.append(new_code_cell(load_code))
    
    # Cells 4..N: One step per pair of cells (markdown + code)
    for step in stepwise_code:
        # Markdown cell with step info
        md_content = f"## {step['title']}\n\n{step['description']}"
        cells.append(new_markdown_cell(md_content))
        
        # Code cell with transformation
        cells.append(new_code_cell(step['python_code']))
    
    # Final cell: Export results
    if has_split:
        export_md = "## Export Results"
        cells.append(new_markdown_cell(export_md))
        
        export_code = """train_df.to_csv("train_processed.csv", index=False)
test_df.to_csv("test_processed.csv", index=False)
print(f"Exported: train_processed.csv ({len(train_df)} rows), test_processed.csv ({len(test_df)} rows)")"""
        cells.append(new_code_cell(export_code))
    else:
        export_md = "## Export Results"
        cells.append(new_markdown_cell(export_md))
        
        export_code = """df.to_csv("processed.csv", index=False)
print(f"Exported: processed.csv ({len(df)} rows)")"""
        cells.append(new_code_cell(export_code))
    
    # Ensure all cells have execution_count = None and outputs = []
    for cell in cells:
        if cell.cell_type == "code":
            cell.execution_count = None
            cell.outputs = []
    
    nb.cells = cells
    
    return nb


def _determine_imports(stepwise_code: list[dict]) -> str:
    """
    Determine required imports based on the steps.
    
    Returns only necessary imports, no application-specific imports.
    """
    import_lines = ["import pandas as pd"]
    
    needs_train_test_split = False
    needs_standard_scaler = False
    needs_minmax_scaler = False
    
    for step in stepwise_code:
        step_type = step["step_type"]
        
        if step_type == "split":
            needs_train_test_split = True
        
        if step_type == "transforms":
            code = step["python_code"]
            if "StandardScaler" in code:
                needs_standard_scaler = True
            if "MinMaxScaler" in code:
                needs_minmax_scaler = True
    
    if needs_train_test_split:
        import_lines.append("from sklearn.model_selection import train_test_split")
    
    scalers = []
    if needs_standard_scaler:
        scalers.append("StandardScaler")
    if needs_minmax_scaler:
        scalers.append("MinMaxScaler")
    
    if scalers:
        import_lines.append(f"from sklearn.preprocessing import {', '.join(scalers)}")
    
    return "\n".join(import_lines)


def notebook_to_string(nb: nbformat.NotebookNode) -> str:
    """
    Serialize notebook to JSON string.
    
    Uses nbformat.writes() as required by V3.1_PRD.md.
    """
    return nbformat.writes(nb)
